---
kind: "operation"
client: "atomist 1.2"
generator:
  name: "NewRugArchiveProject"
  group: "atomist-rugs"
  artifact: "rug-archive"
  version: "0.11.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-archive.git"
    branch: "a881183f4382aa17443b589213889902d2ae69ac"
    sha: "a881183"
  parameters:
    - "project_name": "copedemoarch"
    - "group_id": "russmiles"
    - "version": "0.1.0"
    - "description": "My new project"

